name: Linkfire Live demo

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    #    permissions:
    #      id-token: write
    #      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v2


      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
      - name: Build, tag, and push image to Dockerhub
        env:
          REGISTRY: diegoparra
          REPOSITORY: lf-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
